services:
  - type: web
    name: cos-tuna-demo
    runtime: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_NAME
        value: "Cos Tuna"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        sync: false
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: error
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/html/database/database.sqlite
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: SESSION_DRIVER
        value: file
      - key: FILESYSTEM_DISK
        value: public