import { onBeforeUnmount, onMounted, ref, type Component } from 'vue';
import { adminApi } from './api';
import SelectControl from './select-control';
import { showError, showToast } from './feedback';

type Ordered = { public_id: string; sort_order: number };
type Hero = Ordered & { admin_label: string; eyebrow: string | null; heading: string; supporting_text: string | null; cta_label: string | null; cta_url: string | null; is_active: boolean; desktop_image_path: string | null; mobile_image_path: string | null };
type Section = Ordered & { type: string; eyebrow: string | null; title: string; description: string | null; is_active: boolean; filters_enabled: boolean; products: Product[] };
type Product = { public_id: string; name: string };
type Category = { public_id: string; name: string };
type Tile = Ordered & { label: string; is_active: boolean; desktop_image_path: string | null; mobile_image_path: string | null; category: Category };
type SocialItem = Ordered & { url: string; alt_text: string; image_path: string | null; is_active: boolean };
type Reassurance = Ordered & { icon: string; title: string; text: string; is_active: boolean };
type Editorial = { id?: number; eyebrow: string; heading: string; description: string; cta_label: string; cta_url: string; image_path?: string | null; is_active: boolean; products?: Product[] };
type Brand = { id?: number; heading: string; content: string; is_active: boolean };
type StoreForm = { phone: string; email: string; address: string; whatsapp_url: string; announcement_text: string; footer_statement: string; hero_autoplay_enabled: boolean; social_links: Record<string, string> };

const ContentView: Component = {
    components: { SelectControl },
    setup() {
        const mode = ref('store'); const loading = ref(true); const saving = ref(false); const dirty = ref(false);
        const heroes = ref<Hero[]>([]); const sections = ref<Section[]>([]); const products = ref<Product[]>([]); const categories = ref<Category[]>([]);
        const tiles = ref<Tile[]>([]); const social = ref<SocialItem[]>([]); const reassurance = ref<Reassurance[]>([]);
        const heroEditing = ref<Hero | 'new' | null>(null); const sectionEditing = ref<Section | 'new' | null>(null);
        const tileEditing = ref<Tile | null>(null); const socialEditing = ref<SocialItem | null>(null); const reassuranceEditing = ref<Reassurance | null>(null);
        const modeOptions = [
            { value: 'store', label: 'Coordonnées et pied de page' }, { value: 'heroes', label: 'Diapositives héro' },
            { value: 'sections', label: 'Sections de produits' }, { value: 'tiles', label: 'Grandes tuiles catégories' },
            { value: 'editorial', label: 'Section des incontournables' }, { value: 'reassurance', label: 'Réassurance' },
            { value: 'social', label: 'Galerie sociale' }, { value: 'brand', label: 'Marque et SEO' },
        ];
        const sectionTypeOptions = [{ value: 'new_products', label: 'Nouveaux produits' }, { value: 'best_sellers', label: 'Meilleures ventes' }, { value: 'custom', label: 'Sélection manuelle' }];
        const iconOptions = [{ value: 'payment', label: 'Paiement' }, { value: 'phone', label: 'Téléphone' }, { value: 'delivery', label: 'Livraison' }, { value: 'quality', label: 'Qualité' }];
        const store = ref<StoreForm>({ phone: '', email: '', address: '', whatsapp_url: '', announcement_text: '', footer_statement: '', hero_autoplay_enabled: true, social_links: {} });
        const heroForm = ref({ admin_label: '', eyebrow: '', heading: '', supporting_text: '', cta_label: '', cta_url: '', is_active: false, sort_order: 0, desktop_image: null as File | null, mobile_image: null as File | null });
        const sectionForm = ref({ type: 'custom', eyebrow: '', title: '', description: '', is_active: true, filters_enabled: false, product_public_ids: [] as string[] });
        const tileForm = ref({ category_public_id: '', label: '', is_active: true, desktop_image: null as File | null, mobile_image: null as File | null });
        const socialForm = ref({ url: '', alt_text: '', is_active: true, image: null as File | null });
        const reassuranceForm = ref({ icon: 'payment', title: '', text: '', is_active: true });
        const editorial = ref<Editorial>({ eyebrow: '', heading: '', description: '', cta_label: '', cta_url: '', is_active: true, products: [] });
        const editorialImage = ref<File | null>(null); const editorialProducts = ref<string[]>([]);
        const brand = ref<Brand>({ heading: '', content: '', is_active: true });

        const load = async () => {
            loading.value = true;
            try {
                const [storePayload, heroPayload, sectionPayload, productPayload, categoryPayload, tilePayload, editorialPayload, reassurancePayload, socialPayload, brandPayload] = await Promise.all([
                    adminApi<{ data: StoreForm }>('settings/store'), adminApi<{ data: Hero[] }>('content/banners'), adminApi<{ data: Section[] }>('content/homepage-sections'),
                    adminApi<{ data: { data: Product[] } }>('products?per_page=100'), adminApi<{ data: { data: Category[] } }>('categories?per_page=100'),
                    adminApi<{ data: Tile[] }>('content/items/visual-tiles'), adminApi<{ data: Editorial[] }>('content/items/editorial'),
                    adminApi<{ data: Reassurance[] }>('content/items/reassurance'), adminApi<{ data: SocialItem[] }>('content/items/social'), adminApi<{ data: Brand[] }>('content/items/brand'),
                ]);
                store.value = { ...storePayload.data, social_links: storePayload.data.social_links || {} }; heroes.value = heroPayload.data; sections.value = sectionPayload.data;
                products.value = productPayload.data.data; categories.value = categoryPayload.data.data; tiles.value = tilePayload.data; reassurance.value = reassurancePayload.data; social.value = socialPayload.data;
                if (editorialPayload.data[0]) { editorial.value = editorialPayload.data[0]; editorialProducts.value = editorialPayload.data[0].products?.map((product) => product.public_id) || []; }
                if (brandPayload.data[0]) brand.value = brandPayload.data[0]; dirty.value = false;
            } catch (cause) { showError(cause instanceof Error ? cause.message : 'Chargement impossible.'); } finally { loading.value = false; }
        };
        const markDirty = () => { dirty.value = true; };
        const saveStore = async () => save('settings/store', 'PATCH', store.value, 'Contenu du magasin enregistré.');
        const save = async (path: string, method: string, body: unknown, message: string) => { saving.value = true; try { await adminApi(path, method, body); showToast('success', message); dirty.value = false; await load(); } catch (cause) { showError(cause instanceof Error ? cause.message : 'Enregistrement impossible.'); } finally { saving.value = false; } };
        const asFormData = (values: Record<string, unknown>) => { const body = new FormData(); Object.entries(values).forEach(([key, value]) => { if (value instanceof File) body.append(key, value); else if (Array.isArray(value)) value.forEach((item) => body.append(`${key}[]`, String(item))); else if (value !== null && value !== undefined) body.append(key, typeof value === 'boolean' ? (value ? '1' : '0') : String(value)); }); return body; };
        const imageUrl = (path: string | null | undefined) => path ? `/storage/${path}` : '';
        const chooseFile = (event: Event, assign: (file: File | null) => void) => { assign((event.target as HTMLInputElement).files?.[0] || null); markDirty(); };
        const openHero = (hero?: Hero) => { heroEditing.value = hero || 'new'; heroForm.value = hero ? { admin_label: hero.admin_label, eyebrow: hero.eyebrow || '', heading: hero.heading, supporting_text: hero.supporting_text || '', cta_label: hero.cta_label || '', cta_url: hero.cta_url || '', is_active: hero.is_active, sort_order: hero.sort_order, desktop_image: null, mobile_image: null } : { admin_label: '', eyebrow: '', heading: '', supporting_text: '', cta_label: '', cta_url: '', is_active: false, sort_order: heroes.value.length, desktop_image: null, mobile_image: null }; dirty.value = false; };
        const saveHero = async () => { const existing = typeof heroEditing.value === 'object' ? heroEditing.value : null; await save(existing ? `content/banners/${existing.public_id}` : 'content/banners', 'POST', asFormData(heroForm.value), 'Diapositive enregistrée.'); heroEditing.value = null; };
        const openSection = (section?: Section) => { sectionEditing.value = section || 'new'; sectionForm.value = section ? { type: section.type, eyebrow: section.eyebrow || '', title: section.title, description: section.description || '', is_active: section.is_active, filters_enabled: section.filters_enabled, product_public_ids: section.products.map((product) => product.public_id) } : { type: 'custom', eyebrow: '', title: '', description: '', is_active: true, filters_enabled: false, product_public_ids: [] }; dirty.value = false; };
        const saveSection = async () => { const existing = typeof sectionEditing.value === 'object' ? sectionEditing.value : null; await save(existing ? `content/homepage-sections/${existing.public_id}` : 'content/homepage-sections', existing ? 'PATCH' : 'POST', { ...sectionForm.value, sort_order: existing?.sort_order ?? sections.value.length }, 'Section enregistrée.'); sectionEditing.value = null; };
        const openTile = (tile: Tile) => { tileEditing.value = tile; tileForm.value = { category_public_id: tile.category.public_id, label: tile.label, is_active: tile.is_active, desktop_image: null, mobile_image: null }; };
        const createTile = async () => { const editing = tileEditing.value; await save(editing ? `content/items/visual-tiles/${editing.public_id}` : 'content/items/visual-tiles', 'POST', asFormData({ ...tileForm.value, sort_order: editing?.sort_order ?? tiles.value.length }), editing ? 'Tuile mise à jour.' : 'Tuile ajoutée.'); tileEditing.value = null; tileForm.value = { category_public_id: '', label: '', is_active: true, desktop_image: null, mobile_image: null }; };
        const openSocial = (item: SocialItem) => { socialEditing.value = item; socialForm.value = { url: item.url, alt_text: item.alt_text, is_active: item.is_active, image: null }; };
        const createSocial = async () => { const editing = socialEditing.value; await save(editing ? `content/items/social/${editing.public_id}` : 'content/items/social', 'POST', asFormData({ ...socialForm.value, sort_order: editing?.sort_order ?? social.value.length }), editing ? 'Image sociale mise à jour.' : 'Image sociale ajoutée.'); socialEditing.value = null; socialForm.value = { url: '', alt_text: '', is_active: true, image: null }; };
        const openReassurance = (item: Reassurance) => { reassuranceEditing.value = item; reassuranceForm.value = { icon: item.icon, title: item.title, text: item.text, is_active: item.is_active }; };
        const createReassurance = async () => { const editing = reassuranceEditing.value; await save(editing ? `content/items/reassurance/${editing.public_id}` : 'content/items/reassurance', 'POST', { ...reassuranceForm.value, sort_order: editing?.sort_order ?? reassurance.value.length }, editing ? 'Élément mis à jour.' : 'Élément de réassurance ajouté.'); reassuranceEditing.value = null; reassuranceForm.value = { icon: 'payment', title: '', text: '', is_active: true }; };
        const saveEditorial = async () => { const body = asFormData({ ...editorial.value, image: editorialImage.value, product_public_ids: editorialProducts.value }); await save(editorial.value.id ? `content/items/editorial/${editorial.value.id}` : 'content/items/editorial', 'POST', body, 'Section éditoriale enregistrée.'); editorialImage.value = null; };
        const saveBrand = async () => save(brand.value.id ? `content/items/brand/${brand.value.id}` : 'content/items/brand', 'POST', brand.value, 'Contenu de marque enregistré.');
        const updateItem = async (type: string, item: Ordered & { is_active: boolean }, values: Record<string, unknown>) => save(`content/items/${type}/${item.public_id}`, 'POST', values, 'État enregistré.');
        const removeItem = async (type: string, item: Ordered) => { if (!window.confirm('Supprimer définitivement cet élément non référencé ?')) return; await save(`content/items/${type}/${item.public_id}`, 'DELETE', undefined, 'Élément supprimé.'); };
        const move = async (type: string, items: Ordered[], index: number, delta: number) => { const target = index + delta; if (target < 0 || target >= items.length) return; [items[index], items[target]] = [items[target], items[index]]; await save(`content/${type}/reorder`, 'POST', { items: items.map((item, position) => ({ public_id: item.public_id, sort_order: position })) }, 'Ordre enregistré.'); };
        const productName = (publicId: string) => products.value.find((product) => product.public_id === publicId)?.name || publicId;
        const moveProduct = (selected: string[], index: number, delta: number) => { const target = index + delta; if (target < 0 || target >= selected.length) return; [selected[index], selected[target]] = [selected[target], selected[index]]; dirty.value = true; };
        const beforeUnload = (event: BeforeUnloadEvent) => { if (!dirty.value) return; event.preventDefault(); event.returnValue = ''; };
        onMounted(() => { window.addEventListener('beforeunload', beforeUnload); void load(); }); onBeforeUnmount(() => window.removeEventListener('beforeunload', beforeUnload));
        return { mode, modeOptions, sectionTypeOptions, iconOptions, loading, saving, store, heroes, sections, products, categories, tiles, social, reassurance, heroEditing, heroForm, sectionEditing, sectionForm, tileEditing, socialEditing, reassuranceEditing, tileForm, socialForm, reassuranceForm, editorial, editorialImage, editorialProducts, brand, markDirty, saveStore, imageUrl, chooseFile, openHero, saveHero, openSection, saveSection, openTile, createTile, openSocial, createSocial, openReassurance, createReassurance, saveEditorial, saveBrand, updateItem, removeItem, move, productName, moveProduct };
    },
    template: `<section class="admin-page"><header><div><p class="admin-eyebrow">Contenu / Accueil</p><h1>Contenu du magasin</h1><p class="admin-subtitle">Sections structurées, sans constructeur de pages libre.</p></div><a class="admin-outline" href="/" target="_blank" rel="noopener">Aperçu public</a></header><SelectControl v-model="mode" :options="modeOptions"/><p v-if="loading" class="admin-loading">Chargement…</p>
      <form v-else-if="mode === 'store'" class="category-form" @input="markDirty" @submit.prevent="saveStore"><div class="form-grid"><label>Téléphone<input v-model="store.phone"></label><label>E-mail<input v-model="store.email" type="email"></label><label class="full">Adresse<textarea v-model="store.address"></textarea></label><label>WhatsApp HTTPS<input v-model="store.whatsapp_url"></label><label class="full">Message d’annonce<input v-model="store.announcement_text" maxlength="240"></label><label class="full">Déclaration de marque du pied de page<textarea v-model="store.footer_statement"></textarea></label><label>Instagram<input v-model="store.social_links.instagram"></label><label>Facebook<input v-model="store.social_links.facebook"></label><label class="inline-check">Lecture automatique lente du héro <input v-model="store.hero_autoplay_enabled" type="checkbox"></label></div><footer class="sticky-save-bar"><button class="admin-action" :disabled="saving">{{ saving ? 'Enregistrement…' : 'Enregistrer' }}</button></footer></form>
      <div v-else-if="mode === 'heroes'"><button class="admin-action" @click="openHero()">Nouvelle diapositive</button><form v-if="heroEditing" class="category-form" @input="markDirty" @submit.prevent="saveHero"><div class="form-grid"><label>Libellé interne<input v-model="heroForm.admin_label" required></label><label>Sur-titre<input v-model="heroForm.eyebrow"></label><label class="full">Titre<input v-model="heroForm.heading" required></label><label class="full">Texte<textarea v-model="heroForm.supporting_text"></textarea></label><label>Libellé CTA<input v-model="heroForm.cta_label"></label><label>Lien interne ou HTTPS<input v-model="heroForm.cta_url"></label><label>Image bureau<input type="file" accept="image/jpeg,image/png,image/webp" :required="heroEditing === 'new'" @change="chooseFile($event, file => heroForm.desktop_image = file)"></label><label>Image mobile<input type="file" accept="image/jpeg,image/png,image/webp" @change="chooseFile($event, file => heroForm.mobile_image = file)"></label><label class="inline-check">Active <input v-model="heroForm.is_active" type="checkbox"></label></div><p v-if="saving">Traitement sécurisé de l’image…</p><button class="admin-action" :disabled="saving">Enregistrer</button></form><div class="admin-table"><article v-for="(hero,index) in heroes" :key="hero.public_id"><img v-if="hero.desktop_image_path" class="admin-image-preview" :src="imageUrl(hero.desktop_image_path)" alt=""><strong>{{ hero.admin_label }}</strong><span :class="hero.is_active ? 'admin-badge is-published' : 'admin-badge'">{{ hero.is_active ? 'Active' : 'Inactive' }}</span><button class="text-link" @click="move('banners',heroes,index,-1)" :disabled="index === 0">Monter</button><button class="text-link" @click="move('banners',heroes,index,1)" :disabled="index === heroes.length-1">Descendre</button><button class="text-link" @click="openHero(hero)">Modifier</button></article></div></div>
      <div v-else-if="mode === 'sections'"><button class="admin-action" @click="openSection()">Nouvelle section</button><form v-if="sectionEditing" class="category-form" @input="markDirty" @submit.prevent="saveSection"><div class="form-grid"><label>Type<SelectControl v-model="sectionForm.type" :options="sectionTypeOptions" /></label><label>Sur-titre<input v-model="sectionForm.eyebrow"></label><label>Titre<input v-model="sectionForm.title" required></label><label class="full">Description<textarea v-model="sectionForm.description"></textarea></label><fieldset class="full product-picker"><legend>Sélection des produits</legend><label v-for="product in products" :key="product.public_id" class="inline-check"><input v-model="sectionForm.product_public_ids" type="checkbox" :value="product.public_id"> {{ product.name }}</label><ol class="product-order-list"><li v-for="(publicId,index) in sectionForm.product_public_ids" :key="publicId"><span>{{ productName(publicId) }}</span><button type="button" :disabled="index===0" @click="moveProduct(sectionForm.product_public_ids,index,-1)">Monter</button><button type="button" :disabled="index===sectionForm.product_public_ids.length-1" @click="moveProduct(sectionForm.product_public_ids,index,1)">Descendre</button></li></ol></fieldset><label class="inline-check">Active <input v-model="sectionForm.is_active" type="checkbox"></label><label class="inline-check">Filtres visibles <input v-model="sectionForm.filters_enabled" type="checkbox"></label></div><button class="admin-action">Enregistrer</button></form><div class="admin-table"><article v-for="(section,index) in sections" :key="section.public_id"><strong>{{ section.title }}</strong><span>{{ section.products.length }} produits</span><span>{{ section.is_active ? 'Active' : 'Inactive' }}</span><button class="text-link" @click="move('homepage-sections',sections,index,-1)" :disabled="index === 0">Monter</button><button class="text-link" @click="move('homepage-sections',sections,index,1)" :disabled="index === sections.length-1">Descendre</button><button class="text-link" @click="openSection(section)">Modifier</button></article></div></div>
      <div v-else-if="mode === 'tiles'"><form class="category-form" @input="markDirty" @submit.prevent="createTile"><div class="form-grid"><label>Catégorie<SelectControl v-model="tileForm.category_public_id" :options="categories.map(category => ({value:category.public_id,label:category.name}))" /></label><label>Libellé<input v-model="tileForm.label" required></label><label>Image bureau<input type="file" accept="image/jpeg,image/png,image/webp" :required="!tileEditing" @change="chooseFile($event,file => tileForm.desktop_image=file)"></label><label>Image mobile<input type="file" accept="image/jpeg,image/png,image/webp" @change="chooseFile($event,file => tileForm.mobile_image=file)"></label><label class="inline-check">Active <input v-model="tileForm.is_active" type="checkbox"></label></div><button class="admin-action" :disabled="saving">{{ tileEditing ? 'Enregistrer' : 'Ajouter' }}</button></form><div class="admin-table"><article v-for="(tile,index) in tiles" :key="tile.public_id"><img v-if="tile.desktop_image_path" class="admin-image-preview" :src="imageUrl(tile.desktop_image_path)" alt=""><strong>{{ tile.label }}</strong><span>{{ tile.category.name }}</span><button class="text-link" @click="openTile(tile)">Modifier</button><button class="text-link" @click="updateItem('visual-tiles',tile,{is_active:!tile.is_active})">{{ tile.is_active ? 'Désactiver' : 'Activer' }}</button><button class="text-link" @click="move('items/visual-tiles',tiles,index,-1)" :disabled="index===0">Monter</button><button class="text-link" @click="move('items/visual-tiles',tiles,index,1)" :disabled="index===tiles.length-1">Descendre</button><button class="text-link" @click="removeItem('visual-tiles',tile)">Supprimer</button></article></div></div>
      <form v-else-if="mode === 'editorial'" class="category-form" @input="markDirty" @submit.prevent="saveEditorial"><div class="form-grid"><label>Sur-titre<input v-model="editorial.eyebrow"></label><label>Titre<input v-model="editorial.heading" required></label><label class="full">Description<textarea v-model="editorial.description"></textarea></label><label>Libellé CTA<input v-model="editorial.cta_label"></label><label>Lien interne ou HTTPS<input v-model="editorial.cta_url"></label><label>Image éditoriale<input type="file" accept="image/jpeg,image/png,image/webp" :required="!editorial.id" @change="chooseFile($event,file => editorialImage=file)"></label><img v-if="editorial.image_path" class="admin-image-preview" :src="imageUrl(editorial.image_path)" alt=""><fieldset class="full product-picker"><legend>Produits compacts</legend><label v-for="product in products" :key="product.public_id" class="inline-check"><input v-model="editorialProducts" type="checkbox" :value="product.public_id"> {{ product.name }}</label><ol class="product-order-list"><li v-for="(publicId,index) in editorialProducts" :key="publicId"><span>{{ productName(publicId) }}</span><button type="button" :disabled="index===0" @click="moveProduct(editorialProducts,index,-1)">Monter</button><button type="button" :disabled="index===editorialProducts.length-1" @click="moveProduct(editorialProducts,index,1)">Descendre</button></li></ol></fieldset><label class="inline-check">Active <input v-model="editorial.is_active" type="checkbox"></label></div><button class="admin-action" :disabled="saving">Enregistrer</button></form>
      <div v-else-if="mode === 'reassurance'"><form class="category-form" @input="markDirty" @submit.prevent="createReassurance"><div class="form-grid"><label>Icône approuvée<SelectControl v-model="reassuranceForm.icon" :options="iconOptions" /></label><label>Titre<input v-model="reassuranceForm.title" required></label><label class="full">Texte court<textarea v-model="reassuranceForm.text" required></textarea></label><label class="inline-check">Actif <input v-model="reassuranceForm.is_active" type="checkbox"></label></div><button class="admin-action">{{ reassuranceEditing ? 'Enregistrer' : 'Ajouter' }}</button></form><div class="admin-table"><article v-for="(item,index) in reassurance" :key="item.public_id"><strong>{{ item.title }}</strong><span>{{ item.is_active ? 'Actif' : 'Inactif' }}</span><button class="text-link" @click="openReassurance(item)">Modifier</button><button class="text-link" @click="updateItem('reassurance',item,{is_active:!item.is_active})">{{ item.is_active ? 'Désactiver' : 'Activer' }}</button><button class="text-link" @click="move('items/reassurance',reassurance,index,-1)" :disabled="index===0">Monter</button><button class="text-link" @click="move('items/reassurance',reassurance,index,1)" :disabled="index===reassurance.length-1">Descendre</button><button class="text-link" @click="removeItem('reassurance',item)">Supprimer</button></article></div></div>
      <div v-else-if="mode === 'social'"><form class="category-form" @input="markDirty" @submit.prevent="createSocial"><div class="form-grid"><label>URL sociale HTTPS<input v-model="socialForm.url" type="url" required></label><label>Texte alternatif<input v-model="socialForm.alt_text" required></label><label>Image carrée<input type="file" accept="image/jpeg,image/png,image/webp" :required="!socialEditing" @change="chooseFile($event,file => socialForm.image=file)"></label><label class="inline-check">Active <input v-model="socialForm.is_active" type="checkbox"></label></div><button class="admin-action" :disabled="saving">{{ socialEditing ? 'Enregistrer' : 'Ajouter' }}</button></form><div class="admin-table"><article v-for="(item,index) in social" :key="item.public_id"><img v-if="item.image_path" class="admin-image-preview" :src="imageUrl(item.image_path)" :alt="item.alt_text"><strong>{{ item.alt_text }}</strong><button class="text-link" @click="openSocial(item)">Modifier</button><button class="text-link" @click="updateItem('social',item,{is_active:!item.is_active})">{{ item.is_active ? 'Désactiver' : 'Activer' }}</button><button class="text-link" @click="move('items/social',social,index,-1)" :disabled="index===0">Monter</button><button class="text-link" @click="move('items/social',social,index,1)" :disabled="index===social.length-1">Descendre</button><button class="text-link" @click="removeItem('social',item)">Supprimer</button></article></div></div>
      <form v-else class="category-form" @input="markDirty" @submit.prevent="saveBrand"><label>Titre français<input v-model="brand.heading" required></label><label>Contenu HTML sécurisé<textarea v-model="brand.content" rows="12" required></textarea></label><label class="inline-check">Actif <input v-model="brand.is_active" type="checkbox"></label><footer class="sticky-save-bar"><button class="admin-action" :disabled="saving">Enregistrer</button></footer></form>
    </section>`,
};

export default ContentView;
