import { onMounted, ref, type Component } from 'vue';

type Product = { public_id: string; name: string; has_variants: boolean; stock_quantity: number | null };
type Variant = { public_id: string; sku: string | null; stock_quantity: number; is_active: boolean };
type Detail = Product & { variants: Variant[] };
type Movement = { public_id: string; type: string; quantity_delta: number; quantity_before: number; quantity_after: number; reason: string; product?: { name: string }; variant?: { sku: string | null } };
type Page<T> = { data: T[] };
async function api<T>(path: string, method = 'GET', body?: unknown): Promise<T> { const response = await fetch(`/api/v1/admin/${path}`, { method, credentials: 'same-origin', headers: { Accept: 'application/json', ...(body === undefined ? {} : { 'Content-Type': 'application/json' }) }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) }); if (!response.ok) { const payload = await response.json().catch(() => null) as { message?: string } | null; throw new Error(payload?.message || 'Opération impossible.'); } return response.json() as Promise<T>; }

const InventoryView: Component = {
    setup() {
        const movements = ref<Movement[]>([]); const products = ref<Product[]>([]); const variants = ref<Variant[]>([]); const form = ref({ product_public_id: '', variant_public_id: '', quantity_delta: 0, reason: '' }); const loading = ref(true); const saving = ref(false); const error = ref('');
        const load = async () => { movements.value = (await api<{ data: Page<Movement> }>('inventory/movements?per_page=25')).data.data; };
        onMounted(async () => { try { await Promise.all([load(), api<{ data: Page<Product> }>('products?per_page=100').then(result => { products.value = result.data.data; })]); } catch (cause: unknown) { error.value = cause instanceof Error ? cause.message : 'Erreur'; } finally { loading.value = false; } });
        const selectProduct = async () => { variants.value = []; form.value.variant_public_id = ''; const product = products.value.find(item => item.public_id === form.value.product_public_id); if (!product?.has_variants) return; try { variants.value = (await api<{ data: Detail }>(`products/${product.public_id}`)).data.variants.filter(variant => variant.is_active); } catch (cause: unknown) { error.value = cause instanceof Error ? cause.message : 'Erreur'; } };
        const adjust = async () => { const product = products.value.find(item => item.public_id === form.value.product_public_id); if (product?.has_variants && !form.value.variant_public_id) { error.value = 'Sélectionnez une variante active avant de modifier son stock.'; return; } saving.value = true; error.value = ''; try { await api(`products/${form.value.product_public_id}/inventory-adjustments`, 'POST', { variant_public_id: form.value.variant_public_id || null, quantity_delta: form.value.quantity_delta, reason: form.value.reason }); form.value = { product_public_id: '', variant_public_id: '', quantity_delta: 0, reason: '' }; variants.value = []; await load(); } catch (cause: unknown) { error.value = cause instanceof Error ? cause.message : 'Erreur'; } finally { saving.value = false; } };
        return { movements, products, variants, form, loading, saving, error, selectProduct, adjust };
    },
    // eslint-disable-next-line quotes
    template: `<section class="admin-page"><header><div><p class="admin-eyebrow">Traçabilité</p><h1>Mouvements de stock</h1></div></header><form class="admin-form" @submit.prevent="adjust"><label>Produit<select v-model="form.product_public_id" required @change="selectProduct"><option value="">Choisir</option><option v-for="product in products" :value="product.public_id">{{ product.name }} · {{ product.has_variants ? 'Variantes' : product.stock_quantity }}</option></select></label><label v-if="variants.length">Variante<select v-model="form.variant_public_id" required><option value="">Choisir</option><option v-for="variant in variants" :value="variant.public_id">{{ variant.sku || variant.public_id }} · {{ variant.stock_quantity }}</option></select></label><label>Ajustement<input v-model.number="form.quantity_delta" type="number" required></label><label>Motif<input v-model.trim="form.reason" minlength="3" maxlength="500" required></label><button class="admin-action" :disabled="saving">{{ saving ? 'Enregistrement…' : 'Ajuster le stock' }}</button></form><p v-if="loading">Chargement…</p><p v-else-if="error" class="admin-alert">{{ error }}</p><div v-else class="admin-table"><article v-for="movement in movements" :key="movement.public_id"><div><strong>{{ movement.product?.name || 'Produit archivé' }}<template v-if="movement.variant"> · {{ movement.variant.sku || 'Variante' }}</template></strong><small>{{ movement.reason }}</small></div><span :class="movement.quantity_delta > 0 ? 'status-active' : 'status-muted'">{{ movement.quantity_delta > 0 ? '+' : '' }}{{ movement.quantity_delta }}</span><span>{{ movement.quantity_before }} → {{ movement.quantity_after }}</span><span>{{ movement.type }}</span></article></div></section>`,
};
export default InventoryView;
