import { createApp, ref, onMounted } from 'vue';
import { createPinia } from 'pinia';
import { createRouter, createWebHistory, RouterLink, RouterView } from 'vue-router';

type Page<T> = { data: T[]; current_page: number; last_page: number };
type Product = { public_id: string; name: string; stock_quantity: number | null; is_active: boolean; category?: { name: string }; regular_price_millimes: number };
type Order = { public_reference: string; customer_name: string; status: string; total_millimes: number; created_at: string };
type Movement = { public_id: string; type: string; quantity_delta: number; reason: string; created_at: string; product?: { name: string } };
const money = (value: number) => `${(value / 1000).toFixed(3).replace('.', ',')} TND`;
async function api<T>(path: string): Promise<T> { const response = await fetch(`/api/v1/admin/${path}`, { headers: { Accept: 'application/json' }, credentials: 'same-origin' }); if (!response.ok) throw new Error(response.status === 401 || response.status === 403 ? 'Votre session ne permet pas cet accès.' : 'Les données sont momentanément indisponibles.'); return response.json() as Promise<T>; }
async function write<T>(path: string, method: 'POST' | 'PATCH', body: unknown): Promise<T> { const response = await fetch(`/api/v1/admin/${path}`, { method, credentials: 'same-origin', headers: { Accept: 'application/json', 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); if (!response.ok) throw new Error('Enregistrement impossible. Vérifiez les champs.'); return response.json() as Promise<T>; }
function collection<T>(path: string) { const rows = ref<T[]>([]); const error = ref(''); const loading = ref(true); onMounted(async () => { try { rows.value = (await api<{ data: Page<T> }>(path)).data.data; } catch (cause: unknown) { error.value = cause instanceof Error ? cause.message : 'Erreur'; } finally { loading.value = false; } }); return { rows, error, loading }; }
const Products = { setup: () => collection<Product>('products?per_page=25'), template: '<section class="admin-page"><header><p class="admin-eyebrow">Catalogue</p><h1>Produits</h1></header><p v-if="loading">Chargement…</p><p v-else-if="error" class="admin-alert">{{ error }}</p><div v-else class="admin-table"><article v-for="product in rows" :key="product.public_id"><div><strong>{{ product.name }}</strong><small>{{ product.category?.name || \'Sans catégorie\' }}</small></div><span>{{ product.stock_quantity ?? \'Variantes\' }}</span><span>{{ money(product.regular_price_millimes) }}</span><span :class="product.is_active ? \'status-active\' : \'status-muted\'">{{ product.is_active ? \'Actif\' : \'Inactif\' }}</span></article></div></section>', methods: { money } };
const Orders = { setup: () => collection<Order>('orders?per_page=25'), template: '<section class="admin-page"><header><p class="admin-eyebrow">Opérations</p><h1>Commandes</h1></header><p v-if="loading">Chargement…</p><p v-else-if="error" class="admin-alert">{{ error }}</p><div v-else class="admin-table"><article v-for="order in rows" :key="order.public_reference"><div><strong>{{ order.public_reference }}</strong><small>{{ order.customer_name }}</small></div><span>{{ money(order.total_millimes) }}</span><span class="status-muted">{{ order.status }}</span></article></div></section>', methods: { money } };
const Inventory = { setup: () => collection<Movement>('inventory/movements?per_page=25'), template: '<section class="admin-page"><header><p class="admin-eyebrow">Traçabilité</p><h1>Mouvements de stock</h1></header><p v-if="loading">Chargement…</p><p v-else-if="error" class="admin-alert">{{ error }}</p><div v-else class="admin-table"><article v-for="movement in rows" :key="movement.public_id"><div><strong>{{ movement.product?.name || \'Produit archivé\' }}</strong><small>{{ movement.reason }}</small></div><span :class="movement.quantity_delta > 0 ? \'status-active\' : \'status-muted\'">{{ movement.quantity_delta > 0 ? \'+\' : \'\' }}{{ movement.quantity_delta }}</span><span>{{ movement.type }}</span></article></div></section>' };
const Shell = { components: { RouterLink, RouterView }, template: '<div class="admin-shell"><aside><a class="admin-brand" href="/admin">PASSION<br><small>COSMETIC · ADMIN</small></a><nav><RouterLink to="/products">Produits</RouterLink><RouterLink to="/orders">Commandes</RouterLink><RouterLink to="/inventory">Stock</RouterLink></nav></aside><main><RouterView /></main></div>' };
const router = createRouter({ history: createWebHistory('/admin'), routes: [{ path: '/', redirect: '/products' }, { path: '/products', component: Products }, { path: '/orders', component: Orders }, { path: '/inventory', component: Inventory }] });
createApp(Shell).use(createPinia()).use(router).mount('#admin-app');
