import { onMounted, ref, computed, type Component } from 'vue';
import { adminApi, dinarsToMillimes, millimesToDinars } from './api';
import { showError, showToast } from './feedback';

const ShippingSettingsView: Component = {
    setup() {
        const loading = ref(true); const saving = ref(false); const feeDt = ref(''); const thresholdEnabled = ref(false); const thresholdDt = ref(''); const previewSubtotalDt = ref('100,000');
        const preview = computed(() => { const fee = dinarsToMillimes(feeDt.value) ?? 0; const threshold = dinarsToMillimes(thresholdDt.value); const subtotal = dinarsToMillimes(previewSubtotalDt.value) ?? 0; const free = fee === 0 || (thresholdEnabled.value && threshold !== null && subtotal >= threshold); return { delivery: free ? 'Gratuite' : millimesToDinars(fee) + ' DT', announcement: thresholdEnabled.value && threshold !== null ? `Livraison offerte dès ${millimesToDinars(threshold)} DT` : 'Les frais de livraison sont calculés à la commande.' }; });
        const load = async () => { try { const response = await adminApi<{ data: { fixed_fee_millimes: number; free_threshold_enabled: boolean; free_threshold_millimes: number | null } }>('settings/shipping'); feeDt.value = millimesToDinars(response.data.fixed_fee_millimes); thresholdEnabled.value = response.data.free_threshold_enabled; thresholdDt.value = millimesToDinars(response.data.free_threshold_millimes); } catch (cause) { showError(cause instanceof Error ? cause.message : 'Chargement impossible.'); } finally { loading.value = false; } };
        const save = async () => { const fee = dinarsToMillimes(feeDt.value); const threshold = thresholdDt.value ? dinarsToMillimes(thresholdDt.value) : null; if (fee === null || (thresholdEnabled.value && threshold === null)) return showError('Saisissez des montants valides en DT.'); saving.value = true; try { await adminApi('settings/shipping', 'PATCH', { fixed_fee_millimes: fee, free_threshold_enabled: thresholdEnabled.value, free_threshold_millimes: threshold }); showToast('success', 'Paramètres de livraison enregistrés.'); } catch (cause) { showError(cause instanceof Error ? cause.message : 'Enregistrement impossible.'); } finally { saving.value = false; } };
        onMounted(load); return { loading, saving, feeDt, thresholdEnabled, thresholdDt, previewSubtotalDt, preview, save };
    },
    template: '<section class="admin-page"><header><div><p class="admin-eyebrow">Réglages / Livraison</p><h1>Livraison</h1><p class="admin-subtitle">Une règle unique pour le panier, la commande et la confirmation.</p></div></header><p v-if="loading" class="admin-loading">Chargement…</p><form v-else class="category-form" @submit.prevent="save"><div class="form-grid"><label>Frais de livraison (DT)<input v-model="feeDt" inputmode="decimal" required></label><label class="inline-check">Activer la livraison offerte <input v-model="thresholdEnabled" type="checkbox"></label><label v-if="thresholdEnabled">Seuil de livraison offerte (DT)<input v-model="thresholdDt" inputmode="decimal" required></label></div><section class="settings-preview"><h2>Aperçu</h2><label>Exemple de panier (DT)<input v-model="previewSubtotalDt" inputmode="decimal"></label><p>{{ preview.announcement }}</p><p>Livraison calculée : <strong>{{ preview.delivery }}</strong></p></section><footer class="sticky-save-bar"><button class="admin-action" :disabled="saving">{{ saving ? \'Enregistrement…\' : \'Enregistrer les réglages\' }}</button></footer></form></section>',
};
export default ShippingSettingsView;
